### ISSUE TITLE
Consider defaulting URLs to always return a HTTPS schema

### ISSUE THREAD

**Issue by alister** [henrikbjorn/GravatarBundle#44]
Since the library effectively only returns a URL string, there may be a case to be made to defaulting it to the best practice URL - a secure one.

Another alternative is a config setting (in the config.xml, or local overrides) to force `secure=true`.

**Comment by henrikbjorn** [comment]
Another solution would be to use schema agnostic urls like `//gravatar.com`.

**Comment by alister** [comment]
That is now seen as an anti-pattern.  It’s always safe to request HTTPS assets even if your site is on HTTP, however the reverse is not true.  -- from: http://www.paulirish.com/2010/the-protocol-relative-url/

**Comment by henrikbjorn** [comment]
Feel free to open a PR with the changes.

**Comment by alister** [comment]
How far down the rabbit whole would you like to go? The default-secure URL would not require anything mentioning `$secure`, or similar before the two actual URLs being generated, around https://github.com/henrikbjorn/GravatarBundle/blob/master/GravatarApi.php#L76, which would just be the secure URL.

I'd be inclined to leave the `$secure` parameter in the GravatarExtension where it's being called from userspace, but set the default to true and then trigger a depreciation error on null|false.

**Comment by henrikbjorn** [comment]
We shouldn't deprecate the insecure url's unless Gravatar themselves have deprecated the usage.

But defaulting to secure = true is fine by me.

**Comment by alister** [comment]
With this PR, secure URLs will be produced by default. You can, if required, still get unsecured URLs however.  I'd suggest releasing this as 1.2.0 because of the feature upgrade. I would not call it a BC break though, as the URLs are still entirely valid in every instance, just *better*. :smile:
