### ISSUE TITLE
Would like a new release which contains the commit which allows Symfony 3.*

### ISSUE THREAD

**Issue by msteltenpool** [henrikbjorn/GravatarBundle#47]
I wish to use the 1.1.3 tag, but in it, the allowance of Symfony 3.0 has been removed (since it went from >= to ~), this commit adds it again: https://github.com/henrikbjorn/GravatarBundle/commit/1a35eefa0ec358fe3c547f5f962ed3c67ae743f6

Could you release a new tag where, at the bare minimum, it would contain that commit?

Thanks!

**Comment by createproblem** [comment]
:+1:

**Comment by hboomsma** [comment]
:+1:

**Comment by henrikbjorn** [comment]
Done.
